<Project>
  <PropertyGroup>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

	<ItemGroup>
	<!-- Data Access -->
	<PackageVersion Include="Dapper" Version="2.1.79" />
	<PackageVersion Include="System.Data.SQLite" Version="1.0.119.0" />
	<PackageVersion Include="System.Data.SQLite.Core" Version="1.0.119.0" />

	<!-- Data Generation -->
	<PackageVersion Include="Bogus" Version="35.6.5" />

	<!-- Dependency Injection -->
	<PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
	<PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />

	<!-- Logging -->
	<PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.9" />
	<PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />

	<!-- Graphics -->
	<PackageVersion Include="MonoGame.Framework.WindowsDX" Version="3.8.4.1" />
	<PackageVersion Include="System.Drawing.Common" Version="10.0.9" />

	<!-- Testing -->
	<PackageVersion Include="coverlet.collector" Version="10.0.1" />
	<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
	<PackageVersion Include="xunit.v3" Version="3.2.2" />
	<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
	</ItemGroup>
</Project>
